// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdhynlrmkeqpuimtwefs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkaHlubHJta2VxcHVpbXR3ZWZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTY5MTUsImV4cCI6MjA2NTQ5MjkxNX0.qulizE1PtwYSg-Q4S0R2cz1C-OjU3z5SPEzTsxeR9zU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);